### ISSUE TITLE
General suggestion portal/area?

### ISSUE THREAD

**Issue by FCLC** [hpc-social/mastodon-instance-and-policies#3]
Specific to the mastodon instance, is it worth having a specific sub repository/area for suggestions, and/or generalizing this repository to be "mastodon-polocies-and-suggestions"? 

For example, a suggestion I'd like to submit is to change the favicon of the web interface of mast.hpc.social to use the current logo instead of the default mastodon icon. 

Examples on how to achieve this here https://github.com/mastodon/mastodon/issues/7396 (IIRC at time of posting we're on server version 4.0.2?)

**Comment by FCLC** [comment]
Other example is an area to submit emotes or anything of the sort, in addition to things like changes to the overall configuration of the server. (Character count? )

**Comment by vsoch** [comment]
Maybe issues or discussion here? If the repository is renamed to something more general (that includes policies) it could be a home for that.

**Comment by alansill** [comment]
Right - there isn't a repository on GitHub for the instance itself since that is hosted elsewhere and not even the configurations are under our version management but are handled by the hosting. 

We could rename the repository to something more general, keeping in mind the above, of which policies are just one portion. But discussion of the server can also take place within the instance itself as DMs to admin.

**Comment by vsoch** [comment]
I think it could be nice to have a place for more public discussion? I assume a DM to admin is private.

**Comment by alansill** [comment]
BTW I don't ahve a problem with the dino logo but I don't think it expresses a particular hpc.social identity. That's why the admin account and repository have the default original hpc.social logo. For the Mastodon card I took the default one that came with the server and added the text and that seems to work well when posted on other media. Not sure if a dino would point people to hpc.social in particular but we can open things up for suggestions.

One positive step would be to upload the graphics to GitHub either in this or tha hpc-social.github.io repository and have a section for "official" and one for "contributed" with acceptance via PRs. This is also discussed in https://github.com/hpc-social/hpc-social.github.io/discussions/42.

**Comment by alansill** [comment]
Also this repository *does* have a Discussions area: https://github.com/hpc-social/mastodon-policies/discussions

**Comment by vsoch** [comment]
I made it with the goal of fun branding - the colors match the text one you provided, and the goal was to be a sort of dark, 80s punk cool. I wanted the site (and branding) to be modern and fun. If you look at other tech communities it’s not uncommon to have a mascot.

**Comment by FCLC** [comment]
> Maybe issues or discussion here? If the repository is renamed to something more general (that includes policies) it could be a home for that.

this is what I was thinking, since it seems (to me?) like we're targeting having the git be ground zero for managing things 



> We could rename the repository to something more general, keeping in mind the above, of which policies are just one portion. But discussion of the server can also take place within the instance itself as DMs to admin.

I'm not fond of this unless it's specific to personal issues like moderation. Threads get lost quickly, where as issues/GH discussions are much easier to archive and so on.

**Comment by alansill** [comment]
> I made it with the goal of fun branding - the colors match the text one you provided, and the goal was to be a sort of dark, 80s punk cool. I wanted the site (and branding) to be modern and fun. If you look at other tech communities it’s not uncommon to have a mascot.

Agreed!

**Comment by vsoch** [comment]
At least for the dinosaur, the raw files (xcf) are included https://github.com/hpc-social/hpc-social.github.io/tree/main/assets/img. But I’m pretty sure that post by John Hearns is talking about your text logo @alansill

**Comment by FCLC** [comment]
Realistically it's also worth specifying that suggestions can/should be submitted to [insert what we decide] in the server description? Then mark that issues specific to rules concerns (DMCA, moderation etc.) should be logged via DM to admin? 

As for admin, is it worth a discussion on account access?

**Comment by FCLC** [comment]
(Down with the Flu at the moment, apologies for being slow. Hoping to be in touch with your team at LLNL soon @vsoch <3 )

**Comment by vsoch** [comment]
Oh no! I hope it’s flu and not COVID. Feel better soon @FCLC ! Here is some chicken noodle soup 🍜 and a friend 🧸 ❤️

**Comment by alansill** [comment]
I think this discussion on branding is really about a project covering how to promote hpc.social that belongs or at least could reside in the main web site. The project could be "Promoting hpc.social" and could include ideas discussed in https://github.com/hpc-social/hpc-social.github.io/discussions/42 giving a link to a folder of graphics resources and some rules and guidelines for their use. For example, a good policy might be "You are free to use these resources unaltered to produce promotional items such as pins, stickers, mugs, or other items but should not use them to imply endorsement by hpc.social of any commercial product or project. Usage to promote joining hpc.social discussions or projects including the hpc.social mastodon instance is permitted."

**Comment by alansill** [comment]
Good wishes for your recovery @FCLC!

**Comment by vsoch** [comment]
Good idea @alansill

**Comment by FCLC** [comment]
Not Covid thankfully 😅 Was taking care of my niece last weekend and have been down for the count since. 

Did get my app for the RSE Job in with David A. so hopefully works out 😊

**Comment by vsoch** [comment]
Woot! Did you see the posting from something I shared? I found out I can get a little bonus if someone that found it via me is given an offer and accepts. An unexpected bonus of being loud on social media - I am hopeful haha.

**Comment by alansill** [comment]
> Realistically it's also worth specifying that suggestions can/should be submitted to [insert what we decide] in the server description? Then mark that issues specific to rules concerns (DMCA, moderation etc.) should be logged via DM to admin?
> 
> As for admin, is it worth a discussion on account access?

We have a mastodon-moderators email group in addition to the internal moderation reporting process that is linked explicitly both on the "About" page and on the policies erpository. That should be enough, right?

"Admin" access is another level in the Mastodon area and I'd be happy to share that access. "Owner" access is the highest level and I think should be tied to me now or if we add another for redundancy, it needs to be with the understanding that this is really just for access to the existence of the server itself and so really closely tied to funding responsibility and related topics.

**Comment by vsoch** [comment]
But what about public discussion? 🤔

**Comment by alansill** [comment]
Public discussion of moderation or policies? Or of the Mastodon instance itself? Why not just post on Mastodon?

Thinking this through, I see that the request may be the original one -- rename this to a more general name so that the existing Discussions area can be used for more topics. Is that right?

**Comment by vsoch** [comment]
I think @FCLC is saying we might have a place for general discussion about mastodon, could be policy related but not necessarily. My suggestion was to rename this repository so it’s the catch all for any kind of mastodon discussion, and it would still have a policy directory that is very clearly for that.

**Comment by alansill** [comment]
Okay, done. Please see the renamed repository and README.md info. Close this issue if this meets the needs.

**Comment by FCLC** [comment]
> Woot! Did you see the posting from something I shared? I found out I can get a little bonus if someone that found it via me is given an offer and accepts. An unexpected bonus of being loud on social media - I am hopeful haha.

Both you and Todd! IIRC in the field I put down the both of you 😊 (The cover letter addressed David and yourselves)

**Comment by FCLC** [comment]
> I think @FCLC is saying we might have a place for general discussion about mastodon, could be policy related but not necessarily. My suggestion was to rename this repository so it’s the catch all for any kind of mastodon discussion, and it would still have a policy directory that is very clearly for that.

Correct, renaming the repository was my "easy way out" for catch all mastodon issues/comments/concerns that are indexable

**Comment by vsoch** [comment]
I just beautified up our GitHub org portal so people arriving find all the links they are looking for! This is in .github/profiles/README.md feel free to tweak! 

![image](https://user-images.githubusercontent.com/814322/204158561-851f37fa-3605-4bee-8956-7b3c84e4a901.png)

https://github.com/hpc-social/.github/tree/main/profile

**Comment by alansill** [comment]
Looks good to me. Closing; feel free to reopen if this does not do it.
